FUNC LABEL 0
    MOV STK A VAL 100
    MOV REG 0 STK A
    MOV REG 1 VAL 1
    MOV REG 2 VAL 7
    MOV REG 3 REG 7
    EQU REG 0
    ADD REG 7 REG 0
    ADD REG 7 REG 1
    ADD REG 7 REG 2
    MOV REG 0 STK A
    MOV REG 1 VAL 255
    ADD REG 0 REG 1
    MOV STK A REG 0
    PRINT STK A
    MOV REG 1 VAL 1
    MOV REG 7 REG 3
    RET