FUNC LABEL 0
    MOV STK A VAL 8
    MOV REG 0 STK A
    CAL VAL 1
    MOV STK B VAL 7
    MOV REG 0 STK B
    CAL VAL 1
    RET
FUNC LABEL 1
    MOV REG 1 VAL 249
    MOV REG 2 VAL 1
    MOV REG 3 VAL 4
    ADD REG 0 REG 1
    EQU REG 0
    ADD REG 7 REG 0
    ADD REG 7 REG 2
    ADD REG 7 REG 3
    MOV REG 0 VAL 249
    ADD REG 0 REG 1
    PRINT REG 0
    RET
    MOV REG 0 VAL 2
    ADD REG 0 REG 1
    PRINT REG 0
    RET